project_name: mnist_ci

baseline: false

model: cnn

strategies:
  - name: ewc
    params:
      ewc_lambda: 0.1
      mode: separate  # separate or online
      decay_factor: 0
      keep_importance_data: false

datamodule:
  name: nc_mnist
  params:
    batch_size: 64
    num_workers: 12
    splits: 4

max_epochs: 3
