defaults:
  - _self_
  - datasets
  - biencoder

seed: 42

project_name: continual_ranking
experiment_name: baseline_25
device: gpu

run_type:
  baseline: true
  continual_learning: false
  sizes: [ 0, 20_000, 25_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000, 40_000 ]
