defaults:
  - _self_
  - datasets
  - biencoder
  - strategies
  - experiment: baseline_20k

seed: 42

project_name: continual_ranking
device: gpu
fast_dev_run: false
logging_on: true
negatives_amount: 6
