defaults:
  - _self_
  - datasets
  - biencoder
  - indexing

seed: 42

project_name: continual_ranking
device: gpu
fast_dev_run: false

experiment_name: baseline_25_1n

negatives_amount: 1

run_type:
  baseline: true
  continual_learning: false
  sizes: [ 0, 10_000, 15_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000, 40_000 ]
