defaults:
  - _self_
  - datasets
  - biencoder
  - strategies

seed: 42

project_name: continual_ranking
device: gpu
fast_dev_run: false
logging_on: false

experiment_name: test_fit_loop

negatives_amount: 2

strategy: baseline
#  strategy: naive
#  strategy: ewc
#  strategy: gem
#  strategy: rehearsal

sizes: [ 0, 5, 10 ]
#  sizes: [ 0, 20_000, 25_000, 30_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000 ]
#  sizes: [ 0, 20_000, 25_000, 30_000, 35_000, 40_000 ]
