# @package biencoder

num_workers: 4
max_epochs: -1

batch_size: 2
eval_batch_size: 4
index_batch_size: 32
test_batch_size: 128

max_grad_norm: 1.0

adam_eps: 1e-8
adam_betas: (0.9, 0.999)
learning_rate: 1e-5
weight_decay: 0.0
warmup_steps: 100

sequence_length: 256
dropout: 0.1
