project_name: mnist_ci

#baseline: true
baseline: false

model: cnn

datamodule:
  name: nc_mnist
  params:
    batch_size: 64
    num_workers: 12
    splits: 5

max_epochs: 2

defaults:
  - _self_
  #  - strategies/ewc
  - strategies/gem

hydra:
  run:
    dir: ./log/${now:%Y-%m-%d}/${now:%H-%M-%S}
