# @package datasets
train_base: data/NQ/train.json
val_base: data/NQ/val.json
test_base: data/NQ/test.json

train_cl: data/MSMARCO/passages/train.json
val_cl: data/MSMARCO/passages/val.json
test_cl: data/MSMARCO/passages/test.json

index: data/index.tsv.gz

split_size: 0.2
