# @package datasets
train: data/MSMARCO/passages/wiki_train5.json
val: data/MSMARCO/passages/wiki_train5.json
index: data/MSMARCO/passages/embeddings5.json
test: data/MSMARCO/passages/wiki_train5.json

split_size: 0.2
