# @package datasets
train: /Users/pdaawr/Documents/dtu/5_sem/repo.nosync/continual-ranking/data/MSMARCO/passages/wiki_train5_copy.json
#val: /Users/pdaawr/Documents/dtu/5_sem/repo.nosync/continual-ranking/data/MSMARCO/passages/wiki_train5.json
val: /Users/pdaawr/Documents/dtu/5_sem/repo.nosync/continual-ranking/data/MSMARCO/passages/wiki_dev5.json
test: /Users/pdaawr/Documents/dtu/5_sem/repo.nosync/continual-ranking/data/MSMARCO/passages/wiki_test5.json
embeddings: /Users/pdaawr/Documents/dtu/5_sem/repo.nosync/continual-ranking/data/MSMARCO/passages/embeddings5.json
